pool:
  vmImage: 'ubuntu-16.04'
  name: Azure Pipelines
strategy:
  matrix:
    Python37:
      python.version: '3.7'
#    Python38:
#      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install .
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-cov
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov src/pyskindose --cov-report html --cov-report xml
    ls -l
  displayName: pytest

- task: PublishTestResults@2
  displayName: 'Publish Test Results for Python $(python.version)'
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Python $(python.version)'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage for Python $(python.version)'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: $(System.DefaultWorkingDirectory)/**/htmlcov'
